// DSQSS (Discrete Space Quantum Systems Solver)
// Copyright (C) 2018- The University of Tokyo
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

#ifndef SRC_COMMON_VERSION_H_
#define SRC_COMMON_VERSION_H_

#include <cstdio>
#include <cstring>

// DSQSS_VERSION, DSQSS_GIT_HASH, and DSQSS_VERSION_STRING;
// generated by CMake from the top-level CMakeLists.txt and the commit hash
#include "dsqss_version.h"

namespace dsqss {

// prints the version if "--version" is in the arguments.
// This is for the beginning of main(), before MPI_Init.
inline bool show_version(int argc, char** argv) {
  for (int i = 1; i < argc; ++i) {
    if (std::strcmp(argv[i], "--version") == 0) {
      std::printf("%s\n", DSQSS_VERSION_STRING);
      return true;
    }
  }
  return false;
}

}  // namespace dsqss

#endif  // SRC_COMMON_VERSION_H_
